name: Build Validation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          libvulkan-dev \
          vulkan-utility-libraries-dev \
          libsdl2-dev \
          build-essential

    - name: Verify dependencies
      run: |
        echo "Verifying required dependencies..."
        pkg-config --exists vulkan && echo "✓ Vulkan SDK available"
        pkg-config --exists sdl2 && echo "✓ SDL2 development libraries available"
        echo "✓ CMake version: $(cmake --version | head -1)"
        echo "✓ GCC version: $(gcc --version | head -1)"

    - name: Configure project
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_ASSETS=OFF -DENABLE_EDITOR=OFF

    - name: Build project
      run: |
        cmake --build build --verbose -- -j$(nproc)

    - name: Verify executables
      run: |
        cd build
        echo "Checking build outputs..."
        ls -la pixelengine
        echo "✓ Build completed successfully"name: Build Validation